version: '2'

services:
  
  # SpamScope
  spamscope:
    image: fmantuano/spamscope
    container_name: spamscope
    dns:
        - 8.8.8.8
        - 8.8.4.4
    ports:
        - "8080:8080"
        - "8000:8000"
    volumes:
        # Mails folder
        - /mnt/testing/spamscope:/mnt/mails

        # SpamScope configuration
        - /home/fedelemantuano/Development/Docker/spamscope-dockerfile/conf:/etc/spamscope
    depends_on:
        - elasticsearch

  # Elasticsearch
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    dns:
        - 8.8.8.8
        - 8.8.4.4
    volumes:
        - ./conf:/usr/share/elasticsearch/config

        #  Use that path if you would like to keep the data in a mounted volume
        #- /var/lib/elasticsearch:/usr/share/elasticsearch/data
  
  # Kibana
  kibana:
    image: kibana
    container_name: kibana
    dns:
        - 8.8.8.8
        - 8.8.4.4
    ports:
        - "5601:5601"
    depends_on:
        - elasticsearch
